cg_platform_homepage:
    path:     /
    defaults: { _controller: CGPlatformBundle:Platform:home }
cg_platform_event_add:
    path:     /new
    defaults: { _controller: CGPlatformBundle:Platform:addEvent }
cg_platform_event_view:
    path:     /{id}
    defaults: { _controller: CGPlatformBundle:Platform:showEvent }