parameters:
#    rmo_platform.example.class: RMO\PlatformBundle\Example

services:
#    rmo_platform.example:
#        class: %rmo_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    cg_platform.registration.form.type:
        class: CG\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: cg_user_registration }

    cg_platform.profile.form.type:
        class: CG\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: cg_user_profile }

    cg_platform.change_password.form.type:
        class: CG\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: cg_user_change_password }
