<?php

namespace CG\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationRepository extends EntityRepository
{
}
